/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package login;

import java.io.BufferedReader;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.nio.charset.StandardCharsets;
import java.security.MessageDigest;
import java.security.NoSuchAlgorithmException;
import javax.swing.JOptionPane;

/**
 *
 * @author Usuario
 */
public class Recordar extends javax.swing.JFrame {

    /**
     * Creates new form Recordar
     */
    public Recordar() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        myButton1 = new login.MyButton();
        txtUsuario = new login.MyTextField();
        txtPalabra = new login.MyTextField();
        txtRepNPass = new login.MyPasswordField();
        txtNPass = new login.MyPasswordField();
        jLabel5 = new javax.swing.JLabel();
        myButton2 = new login.MyButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(251, 252, 253));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(58, 59, 69));
        jLabel1.setText("Usuuario:");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(66, 110, -1, -1));

        jLabel2.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(58, 59, 69));
        jLabel2.setText("Nueva contraseña:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(66, 295, -1, -1));

        jLabel3.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(58, 59, 69));
        jLabel3.setText("Palabra clave:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(66, 203, -1, -1));

        jLabel4.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(58, 59, 69));
        jLabel4.setText("Confirmar contraseña:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(262, 295, -1, -1));

        myButton1.setForeground(new java.awt.Color(251, 252, 253));
        myButton1.setText("Aceptar");
        myButton1.setBorderColor(new java.awt.Color(251, 252, 253));
        myButton1.setBorderPainted(false);
        myButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                myButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(myButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(262, 387, 178, 50));

        txtUsuario.setBackground(new java.awt.Color(251, 252, 253));
        txtUsuario.setForeground(new java.awt.Color(58, 59, 69));
        txtUsuario.setBorderColor(new java.awt.Color(209, 211, 225));
        txtUsuario.setCaretColor(new java.awt.Color(187, 187, 187));
        txtUsuario.setFocusBorderColor(new java.awt.Color(75, 110, 175));
        jPanel1.add(txtUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(66, 134, 374, 50));

        txtPalabra.setBackground(new java.awt.Color(251, 252, 253));
        txtPalabra.setForeground(new java.awt.Color(58, 59, 69));
        txtPalabra.setBorderColor(new java.awt.Color(209, 211, 225));
        txtPalabra.setCaretColor(new java.awt.Color(187, 187, 187));
        txtPalabra.setFocusBorderColor(new java.awt.Color(75, 110, 175));
        jPanel1.add(txtPalabra, new org.netbeans.lib.awtextra.AbsoluteConstraints(66, 227, 374, 50));

        txtRepNPass.setBackground(new java.awt.Color(251, 252, 253));
        txtRepNPass.setForeground(new java.awt.Color(58, 59, 69));
        txtRepNPass.setBorderColor(new java.awt.Color(209, 211, 225));
        txtRepNPass.setCaretColor(new java.awt.Color(187, 187, 187));
        txtRepNPass.setFocusBorderColor(new java.awt.Color(75, 110, 175));
        jPanel1.add(txtRepNPass, new org.netbeans.lib.awtextra.AbsoluteConstraints(262, 319, 178, 50));

        txtNPass.setBackground(new java.awt.Color(251, 252, 253));
        txtNPass.setForeground(new java.awt.Color(58, 59, 69));
        txtNPass.setBorderColor(new java.awt.Color(209, 211, 225));
        txtNPass.setCaretColor(new java.awt.Color(187, 187, 187));
        txtNPass.setFocusBorderColor(new java.awt.Color(75, 110, 175));
        jPanel1.add(txtNPass, new org.netbeans.lib.awtextra.AbsoluteConstraints(66, 319, 178, 50));

        jLabel5.setFont(new java.awt.Font("Calibri", 1, 48)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(58, 59, 69));
        jLabel5.setText("Recuperar cotraseña");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(44, 20, -1, -1));

        myButton2.setBackground(new java.awt.Color(251, 252, 253));
        myButton2.setForeground(new java.awt.Color(78, 115, 223));
        myButton2.setText("Cancelar");
        myButton2.setBorderColor(new java.awt.Color(251, 252, 253));
        myButton2.setBorderPainted(false);
        myButton2.setColor(new java.awt.Color(251, 252, 253));
        myButton2.setColorClick(new java.awt.Color(251, 252, 253));
        myButton2.setColorOver(new java.awt.Color(251, 252, 253));
        myButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                myButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(myButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 390, 170, 50));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 512, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 486, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void myButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_myButton1ActionPerformed
        String archivo = "db/usuarios.csv";

        String usuario = txtUsuario.getText();
        String palabra = txtPalabra.getText();
        String nuevaContrasena = txtNPass.getText();
        String confirmarContrasena = txtRepNPass.getText();

        // Verificar que los campos de texto no estén vacíos
        if (usuario.isEmpty() || palabra.isEmpty() || nuevaContrasena.isEmpty() || confirmarContrasena.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Por favor, llene todos los campos", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        // Verificar la autenticación del usuario
        boolean autenticado = false;
        try (BufferedReader br = new BufferedReader(new FileReader(archivo))) {
            String linea;
            while ((linea = br.readLine()) != null) {
                String[] campos = linea.split(",");
                if (campos.length != 5) {
                    System.out.println("Error: la línea no tiene el formato correcto");
                    continue;
                }
                String usuarioArchivo = campos[1];
                String contrasenaArchivo = campos[2];
                String palabraArchivo = campos[3];
                if (usuarioArchivo.equals(usuario) && palabraArchivo.equals(palabra)) {
                    autenticado = true;
                    break;
                }
            }
        } catch (IOException e) {
            System.out.println("Error al leer el archivo: " + e.getMessage());
        }

        if (!autenticado) {
            JOptionPane.showMessageDialog(null, "Nombre de usuario o palabra clave incorrectos", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        // Verificar que las contraseñas coincidan
        if (!nuevaContrasena.equals(confirmarContrasena)) {
            JOptionPane.showMessageDialog(null, "Las contraseñas no coinciden", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        // Encriptar la nueva contraseña
        String nuevaContrasenaEncriptada = null;
        try {
            MessageDigest md = MessageDigest.getInstance("SHA-256");
            byte[] hash = md.digest(nuevaContrasena.getBytes(StandardCharsets.UTF_8));
            StringBuilder sb = new StringBuilder();
            for (byte b : hash) {
                sb.append(String.format("%02x", b));
            }
            nuevaContrasenaEncriptada = sb.toString();
        } catch (NoSuchAlgorithmException e) {
            System.out.println("Error al encriptar la contraseña: " + e.getMessage());
            return;
        }
        // Actualizar el archivo con la nueva contraseña encriptada
        try (BufferedReader br = new BufferedReader(new FileReader(archivo))) {
            StringBuilder sb = new StringBuilder();
            String linea;
            while ((linea = br.readLine()) != null) {
                String[] campos = linea.split(",");
                if (campos.length != 5) {
                    System.out.println("Error: la línea no tiene el formato correcto");
                    continue;
                }
                String id = campos[0];
                String usuarioArchivo = campos[1];
                String contrasenaArchivo = campos[2];
                String palabraArchivo = campos[3];
                String rolArchivo = campos[4];
                if (usuarioArchivo.equalsIgnoreCase(usuario)) {
                    contrasenaArchivo = nuevaContrasenaEncriptada;
                }
                sb.append(String.join(",", id, usuarioArchivo, contrasenaArchivo, palabraArchivo, rolArchivo));
                sb.append("\n");
            }
            try (FileWriter fw = new FileWriter(archivo)) {
                fw.write(sb.toString());
            }
        } catch (IOException e) {
            System.out.println("Error al escribir en el archivo: " + e.getMessage());
        }

        JOptionPane.showMessageDialog(null, "La contraseña ha sido cambiada exitosamente", "Mensaje", JOptionPane.INFORMATION_MESSAGE);
        Login loginWindow = new Login();
        loginWindow.setVisible(true);
        dispose();
    }//GEN-LAST:event_myButton1ActionPerformed

    private void myButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_myButton2ActionPerformed
        Login loginWindow = new Login();
        loginWindow.setVisible(true);
        dispose();
    }//GEN-LAST:event_myButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Recordar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Recordar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Recordar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Recordar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Recordar().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private login.MyButton myButton1;
    private login.MyButton myButton2;
    private login.MyPasswordField txtNPass;
    private login.MyTextField txtPalabra;
    private login.MyPasswordField txtRepNPass;
    private login.MyTextField txtUsuario;
    // End of variables declaration//GEN-END:variables
}
